tunnel: ae770dec-ca0b-469d-b58b-30b8c5ec8069
credentials-file: /etc/cloudflared/ae770dec-ca0b-469d-b58b-30b8c5ec8069.json

ingress:
  - hostname: domain.com
    service: http://localhost:80
  - hostname: www.domain.com
    service: http://localhost:80
  - service: http_status:404
